### ISSUE TITLE
Question regarding getting started

### ISSUE THREAD

**Issue by drfurtado** [pacharanero/create-new-revealjs-template#1]
I am a newbie when comes to reveals.js.
I followed your steps and have it [running](https://github.com/drfurtado/demo-presentation). 

What should go on the YAML header of the Rmd file (presentation)?

Also, where should I keep all Rmd files that will be rendered into HTML? Root dir? I see that there is a HTML file on the root dir, but I could not find the Rmd (or md) file associated with the HTML file.

Any help would be greatly appreciated.

**Comment by pacharanero** [comment]
Hi @drfurtado 

You just edit the Markdown in the index.html

The other extra files are not necessary. Reveal.js is capable of using [markdown form an external file](https://revealjs.com/markdown/#external-markdown), but I've configured this setup to use [markdown from inside the index.html](https://revealjs.com/markdown/):

https://github.com/pacharanero/create-new-revealjs-template/blob/46fff379bc7807132e88700cf3b78964c707e5cb/index.html#L32

I don't know what an Rmd file is.

**Comment by drfurtado** [comment]
> Hi @drfurtado
> 
> You just edit the Markdown in the index.html
> 
> The other extra files are not necessary. Reveal.js is capable of using [markdown form an external file](https://revealjs.com/markdown/#external-markdown), but I've configured this setup to use [markdown from inside the index.html](https://revealjs.com/markdown/):
> 
> https://github.com/pacharanero/create-new-revealjs-template/blob/46fff379bc7807132e88700cf3b78964c707e5cb/index.html#L32
> 
> I don't know what an Rmd file is.

Sorry for the lack of clarification. Rmd. is similar to .md but used in RStudio for R programming. 

I can use .md instead, no problem. So just to clarify, I will not be able to use an external markdown with your template, correct? I like the simplicity of the template you created, but need/want to create the presentation in markdown and render it into HTML files to be displayed in Github pages.

**Comment by pacharanero** [comment]
OK, I had to google it but I worked out you must be using R Studio.

The template, as it is, will already render to GitHub pages. You don't need a pre-compilation step, Reveal.js takes care of rendering the markdown for you.

Test it out at https://pacharanero.github.io/create-new-revealjs-template/ (I just added this, but it's what I do for all my own presentations, GitHub hosting)

If you want to use an external markdown file, you can also do this with the template. You just have to add `="example.md"` after the `data-markdown` tag in the index.html, so that Reveal knows where the external markdown is.

![image](https://user-images.githubusercontent.com/2348385/110996947-9984e300-8374-11eb-94d4-39c2816426b3.png)

**Comment by drfurtado** [comment]
Thank you so much!
Do I have to keep `example.md` in the root dir or it can be placed in a different directory?

**Comment by pacharanero** [comment]
No, I think you can probably put it anywhere, as long as you put the correct relative path in the `data-markdown="/path/to/markdown/file"` section.

I think (although I haven't tried it) that you could have multiple `<section data-markdown="...">` sections, they could each come from a different markdown file, making it potentially quite easy to reuse snippets of content in different files.

**Comment by pacharanero** [comment]
If you are going to do that, I would tend to suggest to create a `markdown/` folder, and put all markdown in there.

My own personal practice is to keep it simple and do everything in index.html. But YMMV

**Comment by drfurtado** [comment]
Again, thank you so much for your help.

**Comment by pacharanero** [comment]
closing as seems to have been sorted out
